machine:
  timezone:
    America/Chicago

  dependencies:
    override:
      - npm install
      - npm install -g hexo-cli

test:
  override:
    - echo "skip test"

deployment:
  prod:
    branch: source
    commands:
      - git config --global user.name "CircleCI"
      - git config --global user.email "circleci@example.org"
      - sed -i'' "s~https://github.com/sob/stonehedges.net.git~https://${GH_TOKEN}:x-oauth-basic@github.com/sob/stonehedges.net.git~" _config.yml
      - hexo clean
      - hexo generate
      - hexo deploy
